### ISSUE TITLE
SIGSEGV when citing multiple .qza files

### ISSUE THREAD

**Issue by ChrisKeefe** [telatin/qax#1]
# Error Message
`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

# When? 
When passing a list of `.qza` files to qax citations:
`>qax citations  ./*.qza`
`SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

It _does not_ fail with a list of `.qzv` files. :thinking: 
`>qax citations ./*.qzv` works fine.

Still fails with either or both of `-r` and `-o`. 

# Running
qax 0.9.1 on  OpenSUSE Tumbleweed

Thanks for putting together a very helpful citation scraper!

**Comment by telatin** [comment]
Hi @ChrisKeefe, I'm sorry this slipped through my inbox. Happy to have a look! :)
Thanks for reporting

PS: I tried with `./bin/qax citations input/*.qza --verbose`, from the repo, and it worked, so I guess I'll have a hard time debugging this...

**Comment by telatin** [comment]
For the moment and without examples of failing inputs, I released v0.9.6 with some more controls, hopefully will help confining the problem! Cheers
